config/routes.rb
Rails.application.routes.draw do
  resources :libros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:isbn, :titulo, :paginas, :editorial)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>    
    <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo center">Logo</a>
      <ul class="left hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li class="active"><a href="collapsible.html">JavaScript</a></li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/libros/_form.html.erb
<%= form_with(model: libro, local: true) do |form| %>
  <% if libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :paginas %>
    <%= form.number_field :paginas %>
  </div>

  <div class="field">
    <%= form.label :editorial %>
    <%= form.text_field :editorial %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libros</h1>

<table>
  <thead>
    <tr>
      <th>Isbn-cambio</th>
      <th>Titulo</th>
      <th>Paginas</th>
      <th>Editorial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.isbn %></td>
        <td><%= libro.titulo %></td>
        <td><%= libro.paginas %></td>
        <td><%= libro.editorial %></td>
        <td><%= link_to 'Show', libro %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>New Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isbn:</strong>
  <%= @libro.isbn %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @libro.titulo %>
</p>

<p>
  <strong>Paginas:</strong>
  <%= @libro.paginas %>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @libro.editorial %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>